### PR TITLE
Nextcloud update fix

### PR DESCRIPTION
**Pull request by volcini**
The tmp folder in /usr/local/www/nextcloud directory and root:wheel as the owner of the nextcloud folder and its files impairs the Nextcloud updater. 
This patch relocates the tmp folder to /usr/local/www/nextcloud-sessions-tmp and changes ownership of the files to www:www.
Solves #1.

### CODE REVIEW

**Comment by miwi-fbsd** [comment]
Hi,

Thank you for all your effort to fix the plugin, I have merged my working repo, can you please give it a try?

**Comment by volcini** [comment]
It still fails at the same spot as #1.
tmp (for sessions) is still inside nextcloud folder. Nextcloud updater stops on detected presence of unknown files and folders.
I fixed pull request and tested on my repo the update to 15.0.0.alpha.
Since the command line utility occ demands config.php to be owned by the user running it, i included a workaround for su -m www -c "...". It works just by simply typing occ and parameters, e.g. occ status.

**Comment by miwi-fbsd** [comment]
Ah, yes that ticket i overlooked, please rebase the patch so i can merge it in.

**Comment by volcini** [comment]
I made a new pull request.

**Pull request closed without merging**
