### PR TITLE
Polishing from Nextcloud review

### PR DESCRIPTION
**Pull request by artonge**
## Major drawbacks in the current version

- Lots of overview Warnings is clean, beside "default phone region" warning.
  - No HTTPS
  - bunch of `.well-known` URL were not resolved correctly
  - No cache
- Limited installed set of applications
- Cron job executed with ajax

## Step taken to improve the situation

- Refactor configuration to be more declarative
  - easier to update (fewer migration scripts)
  - less error-prone (no logic involved)
  - easier to check for specific configuration (not hidden in a default configuration)
- Add HTTPS
  - Self-signed certificates by default (ugly browser warning but still better than HTTP)
  - Possibility to easily generate Letsencrypt certificates if a domain name is configured
- Fix `.well-known` URL resolution
  - nginx configuration sync
  - external port discovery and pass-through
- Add `post_update` script to ease propagation of some configuration changes and migrations
- Add cron job for nextcloud and for TLS certificates renewal
- Add scripts to ease some maintenance tasks
  - DB migrations execution
  - occ shortcut
- Add fail2ban
- Add limit of 100 users
- Add documentation in readme

## HTTPS limitations

For a certain kind of TrueNAS setup, the transition to HTTPS will have to limitations:

- The next update will require a manual action from the admin to add the HTTPS port
- Browser will show a one-time warning if there is no configured domain name as the TLS certificate is self-signed

Both will be communicated in the documentation and on their forum

### CODE REVIEW

**Review by sonicaj — COMMENTED** [review]
Really good work! I have following minor notes:

1. HTTP -> HTTPS redirect does not work with NAT as the redirect redirects to port 443 which when coming to the host would redirect to TrueNAS UI instead of the jail. We should use the host port specified for HTTPS which is available at `/etc/iocage-env`.

2. Changing ports on the host of the jail when using NAT would not sync/update configuration in the jail, this should be overcome by making sure we sync configuration each time the jail starts so that it starts with the updated settings specified from the host. Something like the following should be good:

```
root@orig-nextcloud:~ # cat /usr/local/etc/rc.d/sync-conf
#!/bin/sh
#
# $FreeBSD$
#

# PROVIDE: sync-conf
# BEFORE: nginx

. /etc/rc.subr

do_sync()
{
	/usr/local/bin/sync_configuration;
}

name="sync-conf"
start_cmd='do_sync'
stop_cmd=':'

load_rc_config $name
run_rc_command "$1"
root@orig-nextcloud:~ #
```

**Comment by artonge** [comment]
>     1. HTTP -> HTTPS redirect does not work with NAT as the redirect redirects to port 443 which when coming to the host would redirect to TrueNAS UI instead of the jail. We should use the host port specified for HTTPS which is available at `/etc/iocage-env`.

It should use the host's port. See https://github.com/freenas/iocage-plugin-nextcloud/pull/43/files#diff-3e1e2c9a24c6d2ca50fa32df72b44de0c43bc79b4a09aefa4491835b1bea0909R14
But I did mix up the ports at one point so maybe I need to test that again :)

**Comment by artonge** [comment]
>     2\. Changing ports on the host of the jail when using NAT would not sync/update configuration in the jail, this should be overcome by making sure we sync configuration each time the jail starts so that it starts with the updated settings specified from the host. Something like the following should be good:

Thanks for the pointer. This will indeed smooth things for the admin. I'll add that right away !

**Comment by sonicaj** [comment]
The variable being initialized looks good, however it's not being used in the substitution when the nginx configuration is being generated ;) ( so just making that change should be good :) )

**Comment by artonge** [comment]
It does on my side. Can you try running `sync_configuration` ? If you added the port binding after the first `sync_configuration` it would not have been picked up. `rc.d/sync-conf` will prevent that kind of situation :)

**Comment by artonge** [comment]
I made the `rc.d/sync-conf` script executable. Is it correct?

**Comment by artonge** [comment]
I check and the `rc.d/sync-conf` is not executed on the jail start, can you help with the diagnostic ?

**Review by sonicaj — COMMENTED** [review]
@artonge can you please confirm if you have disabled caching for your browser as browser can cache redirects as well ? ( I have made a short snippet after updating the plugin showing the redirect - this was after updating the plugin and running following commands
```
root@truenas[/mnt/evo/iocage/jails/orig_nextcloud]# iocage set nat_forwards="tcp(80:8282),tcp(443:8283)" o
nat_forwards: tcp(80:8282) -> tcp(80:8282),tcp(443:8283)
root@truenas[/mnt/evo/iocage/jails/orig_nextcloud]# iocage restart o
```
)

https://user-images.githubusercontent.com/17968138/131984651-a08b56d3-83f0-4a4a-9204-d8040ea4eb9e.mov

About the `sync-conf` rc script, i can confirm it's being executed and can be easily checked by adding another line like `echo "running" >> /root/check;` and then restarting the jail from the UI or `iocage restart jailnamehere`. Can you please let me know if there are any issues ?

**Comment by artonge** [comment]
I was able to reproduce your redirection error. Running `sync_configuration` seems to fix it
But I can't reproduce the log output from `sync-conf` by adding `echo "running" >> /root/check;`.

**Comment by sonicaj** [comment]
@artonge the rc script works nicely for me. Can you please share the output of `ls -l /usr/local/etc/rc.d/sync-conf` and the contents of it as well ? I just want to make sure the permissions are good and the script is structured as it should be :)

**Comment by artonge** [comment]
As it is static, it should be the same as you:

```bash
root@nextcloud:~ # ls -l /usr/local/etc/rc.d/sync-conf
-rwxr-xr-x  1 root  wheel  256 Sep  6 05:22 /usr/local/etc/rc.d/sync-conf
```

```bash
root@nextcloud:~ # cat /usr/local/etc/rc.d/sync-conf
#!/bin/sh
#
# $FreeBSD$
#

# PROVIDE: sync-conf
# BEFORE: nginx

. /etc/rc.subr

do_sync()
{
        echo "running" >> /root/check;
        /usr/local/bin/sync_configuration;
}

name="sync-conf"
start_cmd='do_sync'
stop_cmd=':'

load_rc_config $name
run_rc_command "$1"
```

```bash
root@truenas[~]# iocage restart nextcloud
* Stopping nextcloud
  + Executing prestop OK
  + Stopping services OK
  + Tearing down VNET OK
  + Removing devfs_ruleset: 1000 OK
  + Removing jail process OK
  + Executing poststop OK
nextcloud: nat requires nat_interface, using vtnet0
No default gateway found for ipv6.
* Starting nextcloud
  + Started OK
  + Using devfs_ruleset: 1000 (iocage generated default)
  + Configuring VNET OK
  + Using IP options: vnet
iocage restar  + Starting services OK
  + Executing poststart OK
```

**Comment by sonicaj** [comment]
@artonge i am not able to reproduce, i updated the plugin from old installation to the newer version and then modified the rc script and ran the following commands:
```
root@truenas[~]# iocage console o
Last login: Wed Sep  1 12:01:59 on pts/0
FreeBSD 12.2-RELEASE-p9 2ee62d665f0(HEAD) TRUENAS

Welcome to FreeBSD!

Release Notes, Errata: https://www.FreeBSD.org/releases/
Security Advisories:   https://www.FreeBSD.org/security/
FreeBSD Handbook:      https://www.FreeBSD.org/handbook/
FreeBSD FAQ:           https://www.FreeBSD.org/faq/
Questions List: https://lists.FreeBSD.org/mailman/listinfo/freebsd-questions/
FreeBSD Forums:        https://forums.FreeBSD.org/

Documents installed with the system are in the /usr/local/share/doc/freebsd/
directory, or can be installed later with:  pkg install en-freebsd-doc
For other languages, replace "en" with a language code like de or fr.

Show the version of FreeBSD installed:  freebsd-version ; uname -a
Please include that output and any error messages when posting questions.
Introduction to manual pages:  man man
FreeBSD directory layout:      man hier

Edit /etc/motd to change this login announcement.
root@orig-nextcloud:~ # cat /usr/local/etc/rc.d/sync-conf
#!/bin/sh
#
# $FreeBSD$
#

# PROVIDE: sync-conf
# BEFORE: nginx

. /etc/rc.subr

do_sync()
{
        echo "running" >> /root/check;
	/usr/local/bin/sync_configuration;
}

name="sync-conf"
start_cmd='do_sync'
stop_cmd=':'

load_rc_config $name
run_rc_command "$1"
root@orig-nextcloud:~ # rm -f check
root@orig-nextcloud:~ # ls -l /root/check
ls: /root/check: No such file or directory
root@orig-nextcloud:~ # ls -l /usr/local/etc/rc.d/sync-conf
-rwxr-xr-x  1 root  wheel  263 Sep  8 00:00 /usr/local/etc/rc.d/sync-conf
root@orig-nextcloud:~ # exit
logout
root@truenas[~]# iocage restart o
* Stopping orig_nextcloud
  + Executing prestop OK
  + Stopping services OK
  + Tearing down VNET OK
  + Removing devfs_ruleset: 1000 OK
  + Removing jail process OK
  + Executing poststop OK
orig_nextcloud: nat requires nat_interface, using vtnet0
No default gateway found for ipv6.
* Starting orig_nextcloud
  + Started OK
  + Using devfs_ruleset: 1000 (iocage generated default)
  + Configuring VNET OK
  + Using IP options: vnet
  + Starting services OK
  + Executing poststart OK
root@truenas[~]# iocage console o
Last login: Wed Sep  8 00:01:04 on pts/0
FreeBSD 12.2-RELEASE-p9 2ee62d665f0(HEAD) TRUENAS

Welcome to FreeBSD!

Release Notes, Errata: https://www.FreeBSD.org/releases/
Security Advisories:   https://www.FreeBSD.org/security/
FreeBSD Handbook:      https://www.FreeBSD.org/handbook/
FreeBSD FAQ:           https://www.FreeBSD.org/faq/
Questions List: https://lists.FreeBSD.org/mailman/listinfo/freebsd-questions/
FreeBSD Forums:        https://forums.FreeBSD.org/

Documents installed with the system are in the /usr/local/share/doc/freebsd/
directory, or can be installed later with:  pkg install en-freebsd-doc
For other languages, replace "en" with a language code like de or fr.

Show the version of FreeBSD installed:  freebsd-version ; uname -a
Please include that output and any error messages when posting questions.
Introduction to manual pages:  man man
FreeBSD directory layout:      man hier

Edit /etc/motd to change this login announcement.
root@orig-nextcloud:~ # cat /root/check
running
root@orig-nextcloud:~ #
```
We can see `/root/check` has been created and it has `running` added to it ?

**Review by sonicaj — COMMENTED** [review]
If user switches from NAT to DHCP or the ip address changes ( manual changes to ip address via UI ) we should be updating the self generated certificate as well which i don't think is happening currently. Can we please accommodate that change as well ? I also wonder if it's perhaps better to set CN to `localhost` instead and users wanting more control/privacy can generate their own certs and update the accordingly ?

**Comment by artonge** [comment]
> We can see /root/check has been created and it has running added to it ?

Fuck, I feel stupid, I thought that `root/check` was a special file and I was expecting to see anything written to it forwarded to the `iocage update` output.
After running `cat` on the file I can see the `running` output.

**Comment by artonge** [comment]
> I also wonder if it's perhaps better to set CN to localhost instead and users wanting more control/privacy can generate their own certs and update the accordingly ?

Just push the change to have CN = localhost. Not sure what is the reasoning for that though :)

**Comment by sonicaj** [comment]
@artonge reasoning for that is that we should either update the cert each time network changes come into effect and nextcloud is using our generated cert or we should use a generic value where the users who are seeming more control/privacy can consume their own certs by setting/updating them.

**Comment by sonicaj** [comment]
The redirection issue still persists even after making sure `sync-conf` is running. I think we are not updating the port correctly in nginx configuration, can you confirm please ?

**Review by sonicaj — APPROVED** [review]
Good work ; )

**Comment by GladOSkar** [comment]
Hi, sorry for necroing. I just updated and now can't add users anymore because of the user limit. May i ask what was the reason for this change? Thanks! We're a student project and can't pay for licenses, but do need the amount of users...

**Pull request merged**
